### PR TITLE
AES Proposal

### PR DESCRIPTION
**Pull request by vbar-ebsco**
The Okapi Asynchronous Event Service (AES) proposal

### CODE REVIEW

**Comment by adamdickmeiss** [comment]
We created a document outlining how at least some of the AES could be implemented.
Hope this gdoc link works: https://docs.google.com/document/d/1L0qJ6VEmlKU4UCfznnc7du9qPZpjVq3DhcW68leIgEY/edit?usp=sharing

**Comment by hjiebsco** [comment]
> We created a document outlining how at least some of the AES could be implemented.
> Hope this gdoc link works: https://docs.google.com/document/d/1L0qJ6VEmlKU4UCfznnc7du9qPZpjVq3DhcW68leIgEY/edit?usp=sharing

Thanks @adamdickmeiss! I have a few questions 1) do we allow mod-aes to communicate with external systems directly? Or should all communication go through Okapi? 2) do we allow the underlying message store (Kafka or Rabbit) to send or receive messages from external systems? I thought it should be hidden from everything else except mod-aes. 3) So the message flow within FOLIO will be something like this: producer modules publish messages to aes-publish end points provided by mod-aes, and then mod-aes deliveries messages (based on scope) to consumer modules that implement aes-receive interface, correct? Is there a way to re-deliver a message or maybe consumer wants to retrieve some old messages?

**Comment by adamdickmeiss** [comment]
> 
> Thanks @adamdickmeiss! I have a few questions 1) do we allow mod-aes to communicate with external systems directly? Or should all communication go through Okapi? 2) do we allow the underlying message store (Kafka or Rabbit) to send or receive messages from external systems? I thought it should be hidden from everything else except mod-aes. 3) So the message flow within FOLIO will be something like this: producer modules publish messages to aes-publish end points provided by mod-aes, and then mod-aes deliveries messages (based on scope) to consumer modules that implement aes-receive interface, correct? Is there a way to re-deliver a message or maybe consumer wants to retrieve some old messages?

1. Yes. mod-aes can communicate with external systems directly - I assume with direct communication you mean by the means of Kafka or other..  So .. with 2 . I don't understand what that is different .. the messaging system managing by mod-aes will also be to receive messagess from the outside. 3. .. re-deliver.. If that is something the messaging system provides support for.. No hinder in re-deliver ..I assume that when we send a message via aes-receive, the module will signal in its HTTP whether successfully handled or not (and perhaps the messaging system can deliver).. I guess it depends on the messaging system.. I dunno. The aes-receive interface (the wrapper) should hold what's "common" sense for a message queue (details left out)

mod-aes.. Like storage modules ideally will bet configured by a few set of environment variables for MessageQueue networking, configuration etc.. The exact set will surely be determined by the system of choice.

**Comment by craigmcnally** [comment]
Is the provisioning of AES targets (queues/topics/etc.) handled externally?

**Comment by craigmcnally** [comment]
While there are obviously a set of features shared by or common to all of the various messaging systems mentioned, it's probably safe to say there are some features that are only supported by one or a subset of the supported messaging protocols.  I'm thinking along the lines of message durability, etc.   Is there a way for a module to specify that it needs to use a particular messaging system, or at least one that supports certain features?  Would that be handled via the "scope" array?

**Comment by craigmcnally** [comment]
If I understand correctly, the "aes-publish" and "aes-receive" interfaces tell mod-aes that a module is a publisher or receiver of messages... but what about dependencies?  Is it reasonable to develop a module that can only operate if AES is setup and enabled?  If so, how?  If not, does that mean that modules must define both synchronous and asynchronous implementations?

**Comment by craigmcnally** [comment]
Is there a single messaging system/protocol for the entire FOLIO instance, or are multiple supported simultaneously?

**Comment by skoczko** [comment]
> Thanks @adamdickmeiss! I have a few questions 1) do we allow mod-aes to communicate with external systems directly? Or should all communication go through Okapi? 2) do we allow the underlying message store (Kafka or Rabbit) to send or receive messages from external systems? I thought it should be hidden from everything else except mod-aes. 3) So the message flow within FOLIO will be something like this: producer modules publish messages to aes-publish end points provided by mod-aes, and then mod-aes deliveries messages (based on scope) to consumer modules that implement aes-receive interface, correct? Is there a way to re-deliver a message or maybe consumer wants to retrieve some old messages?

I'll take a stab at answering some of this while Adam is away. Here's my take:

1. Yes. If by "directly" you mean "through the underlying message queue implementation" but in practice I think it should be limited to "external" systems hosted along with FOLIO (e.g reporting, BI/analytics, audit, workflow, etc), not external systems in terms of truly remote systems like other ILSes, resource sharing systems, etc. For those FOLIO APIs and standard protocols (like NCIP, OAI-PMH, z3950) should be used, including message-oriented FOLIO APIs if needed. I don't think we should be exposing the MQ implementation over the Internet, potentially with the exception of establishing a "tunnel" between two remote FOLIO systems.
2. Yes. I think there is a major difference between MQs and RDBS. RDBS implements a structured schema that often servers as a persistent data structure for the module/program (with data layout often made complex because of perf optimization, indexing etc). Exposing that schema directly is problematic and limits how the module can evolve and organize its internal data storage. MQs don't enforce structured schemas for events (that's up to the clients to agree/establish) and events are part of an immutable stream so there's no harm in accessing the data directly (unlike RDBS where by accessing it directly you could break validation/constraints enforced by the business logic).
3. Yes, that's precisely the flow. I think in terms of resending messages or setting "delivery" guarantees, this should be part of mod-aes own configuration. It could be set differently for different "scopes" depending on their purpose. It could also be specific to the underlying MQ implementation and its configuration.

**Comment by skoczko** [comment]
> If I understand correctly, the "aes-publish" and "aes-receive" interfaces tell mod-aes that a module is a publisher or receiver of messages... but what about dependencies? Is it reasonable to develop a module that can only operate if AES is setup and enabled? If so, how? If not, does that mean that modules must define both synchronous and asynchronous implementations?

`aes-publish` is the interface provided by mod-aes for the purpose of sending messages through it. So dependencies are just standard FOLIO dependencies: any module wanting to send messages declares dependency on `aes-publish` and Okapi will satisfy the dependency (with available mod-aes implementation) at installation time.

For the message subscription part it's the module itself that implements the `aes-receive` interface with type `multiple` (this is critical as there will be many subscribers) and sets the `scope` parameter to indicate the type of messages it is interested in (this is similar to subscribing to a particular channel or topic in a MQ). This decouples message producers and consumers -- there's no direct dependency between them. If for whatever reason you wanted to establish this dependency -- assume you want to make sure that when consumer module is installed a specific producer is also installed, e.g mod-circulation-audit makes little sense without mod-circulation -- you would do this by depending on a regular FOLIO interface. One extension that Adam doesn't propose, but I could see as something useful, is to add the "scope" parameter to the interface implemented by the producer, so the type of produced messages (and not only consumed) is also indicated -- it's not required per se but could help clarity when we have many modules producing same type of messages.

**Comment by hjiebsco** [comment]
> 1. Yes. If by "directly" you mean ...
> 2. Yes. I think ...
> 3. Yes, that's precisely the flow ...
@skoczko thanks for your reply. If I understand it correctly that the MQ is accessible by other modules (not hidden behind mod-aes), does that mean the message flow can be simplified to this (assuming FOLIO will settle down on one MQ): module gets MQ connection info from mod-config (through Okapi), and then connects to MQ directly to create topic and publish messages. On the consumer side, module can do the same and subscribe/retrieve messages from MQ directly as needed. Then we do not even need mod-aes and aes-publish/receive interfaces. The potential drawback is we have one central point (Okapi) before, but two now (Okapi and MQ). Is this right? I probably missed something. :thinking:

**Comment by hjiebsco** [comment]
> This may be getting into the details of implementation but I think it would be useful if the AES Rules selection-criteria included transaction method (e.g. POST, GET).

Totally agree, @mis306lu, @vbar-ebsco and I discussed that earlier. Currently Okapi passes the client request method as a header `X-Okapi-request-method` to Pre/Post filters. So depends on the implementation, the request method could potentially be part of the header selection-criteria.

**Comment by craigmcnally** [comment]
As discussed at the [7/20/2022 Technical Council meeting](https://wiki.folio.org/display/TC/2022-07-20+Meeting+notes), I'm closing this as quite outdated.

**Pull request closed without merging**
